In [1]:
import os
import sys
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# 1. LOAD THE LOCAL CSV FILE
script_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in locals() else os.getcwd()
file_name = "knn.csv" 
file_path = os.path.join(script_dir, file_name)

try:
    dataset = pd.read_csv(file_path)
    print(f"Successfully loaded '{file_name}' from: {file_path}")
    print("Detected Dataset Shape:", dataset.shape)
    print("\nYour Actual Columns are:", list(dataset.columns))
    print("\nFirst 3 rows of your data:\n", dataset.head(3))
except FileNotFoundError:
    print(f"\n[ERROR] Could not find '{file_name}'")
    sys.exit()

# 2. SEPARATE FEATURES AND TARGETS CORRECLTY FOR A 3-COLUMN SHAPE
# X will take columns 0 and 1. y will take column 2 (the last column).
X = dataset.iloc[:, :-1].values  
y = dataset.iloc[:, -1].values   

print(f"\nExtracted {X.shape[1]} Feature columns and 1 Label column.")

# 3. SPLIT TRAINING AND TESTING GROUPS
# Removed 'stratify=y' temporarily because if a class has only 1 sample in a 25-row file, stratification fails.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# 4. FEATURE SCALING
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train) 
X_test = scaler.transform(X_test)       

# 5. INITIALIZE AND TRAIN KNN CLASSIFIER
print("\nTraining KNN Model...")
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)

# 6. EXECUTE EVALUATION MATRIX
y_pred = classifier.predict(X_test)
print("\n=== CLASSIFIER CONFUSION MATRIX ===")
print(confusion_matrix(y_test, y_pred))
print("\n=== CLASSIFIER PERFORMANCE REPORT ===")
print(classification_report(y_test, y_pred, zero_division=0))

# 7. AUTOMATIC LIVE PREDICTION 
# Dynamically builds an inference vector matching your file's exact feature count (2 columns)
custom_features = [9.1, 85] # Cleaned up your original sample values [[9.1, 85, 8.]] to match your shape
raw_inference_sample = [custom_features[:X.shape[1]]] 

print(f"\nEvaluating customized query vector: {raw_inference_sample}")
scaled_inference_sample = scaler.transform(raw_inference_sample)

predicted = classifier.predict(scaled_inference_sample)
print("--> Predicted Output Label:", predicted)


Successfully loaded 'knn.csv' from: c:\Users\student\Desktop\ML202415099\knn.csv
Detected Dataset Shape: (25, 3)

Your Actual Columns are: ['Weight(x2)', 'Height(y2)', 'Class']

First 3 rows of your data:
    Weight(x2)  Height(y2)        Class
0          51         167  Underweight
1          66         177       Normal
2          75         169   Overweight

Extracted 2 Feature columns and 1 Label column.

Training KNN Model...

=== CLASSIFIER CONFUSION MATRIX ===
[[2 0 0]
 [2 0 0]
 [0 0 1]]

=== CLASSIFIER PERFORMANCE REPORT ===
              precision    recall  f1-score   support

      Normal       0.50      1.00      0.67         2
  Overweight       0.00      0.00      0.00         2
 Underweight       1.00      1.00      1.00         1

    accuracy                           0.60         5
   macro avg       0.50      0.67      0.56         5
weighted avg       0.40      0.60      0.47         5


Evaluating customized query vector: [[9.1, 85]]
--> Predicted Output Label: ['Ov

In [32]:
import os
import sys

# Failsafe environment flag alignment
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Mutes redundant hardware warning lines

try:
    import tensorflow as tf
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import Dense
    from sklearn.model_selection import train_test_split
    from sklearn.datasets import make_blobs
except ImportError as e:
    print(f"[IMPORT ERROR] Missing required libraries: {e}")
    print("Please run: pip install tensorflow scikit-learn pandas numpy==1.26.4")
    sys.exit()

print(f"TensorFlow Backend Activated Successfully! (v{tf.__version__})")

# 1. GENERATE DATA CLUSTERS
# Creates 100 coordinates across 2 structural nodes (features)
X, y = make_blobs(n_samples=100, centers=2, n_features=2, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# 2. DEFINE SEQUENTIAL LAYER ARCHITECTURE
model = Sequential()
# Input layer expecting 2 coordinate vectors mapping to 12 hidden processing nodes
model.add(Dense(12, input_dim=2, activation='relu'))
# Secondary dense hidden extraction layer matching processing nodes
model.add(Dense(8, activation='relu'))
# Output classification layer executing a sigmoid probability curve bounds [0, 1]
model.add(Dense(1, activation='sigmoid'))

# 3. COMPILE SYSTEM COMPONENT WEIGHTS
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# 4. TRAINING EXECUTION
print("\nTraining the sequential layers across 100 epochs...")
model.fit(X_train, y_train, epochs=100, batch_size=10, verbose=0)

# 5. MODEL PERFORMANCE METRICS EVALUATION
# return_dict=True maps explicit string keys straight to numerical output metrics
train_eval = model.evaluate(X_train, y_train, verbose=0, return_dict=True)
test_eval = model.evaluate(X_test, y_test, verbose=0, return_dict=True)

# 6. OUTPUT METRIC READOUTS
print("\n============= MODEL PERFORMANCE METRICS =============")
print(f"Training Set  -> Loss: {train_eval['loss']:.4f} | Accuracy: {train_eval['accuracy'] * 100:.2f}%")
print(f"Test Holdout  -> Loss: {test_eval['loss']:.4f} | Accuracy: {test_eval['accuracy'] * 100:.2f}%")
print("=====================================================")

# 7. LIVE SYSTEM INFERENCE LOOP PREDICTION
# Direct multi-feature row array mapping an abstract location profile
raw_custom_entry = [[2.1, 0.8]]
predicted_probability = model.predict(raw_custom_entry, verbose=0)
predicted_class = (predicted_probability > 0.5).astype("int32")

print(f"\nInference evaluation on coordinate vector {raw_custom_entry}:")
print(f"Calculated Fraud/Cluster Probability: {predicted_probability[0][0] * 100:.2f}%")
print(f"Assigned Output Target Label: Cluster Group {predicted_class[0][0]}")


TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [30]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_blobs

print(f"NumPy Version Loaded: {np.__version__}")
print("Pure Mathematical Matrix Mode Activated (100% stable in VS Code!)")

# 1. GENERATE THE ARTIFICIAL DATA CLUSTERS
X, y = make_blobs(n_samples=100, centers=2, n_features=2, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Reshape target labels to formal matrix column vectors (Nx1)
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

# 2. INITIALIZE NETWORK SHAPE WEIGHTS & BIASES
np.random.seed(42)
input_nodes = 2
hidden_nodes = 12
output_nodes = 1

# Randomize the connective tensor nodes
weights_hidden = np.random.randn(input_nodes, hidden_nodes) * 0.1
bias_hidden = np.zeros((1, hidden_nodes))

weights_output = np.random.randn(hidden_nodes, output_nodes) * 0.1
bias_output = np.zeros((1, output_nodes))

# 3. DEFINE ACTIVATION FUNCTIONS (Sigmoid probability compression mapping)
def sigmoid(x):
    return 1 / (1 + np.exp(-np.clip(x, -500, 500))) # np.clip prevents math overflow overflow drops

def sigmoid_derivative(x):
    return x * (1 - x)

# 4. STEP-BY-STEP MANUALLY SIMULATED TRAINING LOOP (Backpropagation)
learning_rate = 0.1
epochs = 100

print("\nOptimizing network weights across 100 epochs...")
for epoch in range(epochs):
    # --- PHASE A: FORWARD PROPAGATION PASS ---
    hidden_layer_input = np.dot(X_train, weights_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)
    
    output_layer_input = np.dot(hidden_layer_output, weights_output) + bias_output
    predicted_output = sigmoid(output_layer_input)
    
    # --- PHASE B: BACKPROPAGATION PASS (Error calculus resolution) ---
    error_delta = y_train - predicted_output
    
    # Compute gradients for output mapping
    d_predicted_output = error_delta * sigmoid_derivative(predicted_output)
    
    # Track backwards and solve hidden layer error weight distribution
    error_hidden_layer = d_predicted_output.dot(weights_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)
    
    # --- PHASE C: WEIGHT ADJUSTMENT MATRICES ---
    weights_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    
    weights_hidden += X_train.T.dot(d_hidden_layer) * learning_rate
    bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

# 5. GENERALIZATION PERFORMANCE METRICS EVALUATION
hidden_test = sigmoid(np.dot(X_test, weights_hidden) + bias_hidden)
test_predictions = sigmoid(np.dot(hidden_test, weights_output) + bias_output)

# Map continuous sigmoid bounds down to absolute binary target tags (0 or 1)
train_classes = (predicted_output > 0.5).astype(int)
test_classes = (test_predictions > 0.5).astype(int)

# Extract final network execution bounds manually
train_accuracy = np.mean(train_classes == y_train) * 100
test_accuracy = np.mean(test_classes == y_test) * 100

print("\n============= MODEL PERFORMANCE METRICS =============")
print(f"Custom Network Training Accuracy : {train_accuracy:.2f}%")
print(f"Custom Network Test Accuracy     : {test_accuracy:.2f}%")
print("=====================================================")

# 6. LIVE SINGLE-SAMPLE INFERENCE
raw_custom_entry = np.array([[2.1, 0.8]])
hidden_inf = sigmoid(np.dot(raw_custom_entry, weights_hidden) + bias_hidden)
predicted_prob = sigmoid(np.dot(hidden_inf, weights_output) + bias_output)
assigned_label = 1 if predicted_prob > 0.5 else 0

print(f"\nInference execution on vector {raw_custom_entry.tolist()}:")
print(f"Calculated Target Group Probability: {predicted_prob[0][0] * 100:.2f}%")
print(f"Assigned Output Classification Class: Cluster Group {assigned_label}")


NumPy Version Loaded: 2.2.6
Pure Mathematical Matrix Mode Activated (100% stable in VS Code!)

Optimizing network weights across 100 epochs...

============= MODEL PERFORMANCE METRICS =============
Custom Network Training Accuracy : 92.86%
Custom Network Test Accuracy     : 96.67%

Inference execution on vector [[2.1, 0.8]]:
Calculated Target Group Probability: 99.00%
Assigned Output Classification Class: Cluster Group 1
